[font]
size = 12.0

[font.normal]
family = "FiraCode Nerd Font"
style = "Regular"

[window]
startup_mode = "Maximized"
decorations = "None"
opacity = 0.8

[window.padding]
x = 15
y = 15

[selection]
save_to_clipboard = true
